class CreateQuestions < ActiveRecord::Migration
  def change
    create_table :forms do |t|
        t.integer :user_id
        t.string :gh_ami_cc_only, default: "0"
        t.string :gh_ami_cc_plus, default: "0"
        t.string :gh_ami_reg_med, default: "0"
        t.string :gh_ami_invasive, default: "0"
        t.string :gh_ami_respirator, default: "0"
        t.string :gh_ami_dialysis, default: "0"
        t.string :gh_ami_cpr, default: "0"
        t.string :gh_bi_cc_only, default: "0"
        t.string :gh_bi_cc_plus, default: "0"
        t.string :gh_bi_reg_med, default: "0"
        t.string :gh_bi_invasive, default: "0"
        t.string :gh_bi_respirator, default: "0"
        t.string :gh_bi_dialysis, default: "0"
        t.string :gh_bi_cpr, default: "0"
        t.string :dh_ami_cc_only, default: "0"
        t.string :dh_ami_cc_plus, default: "0"
        t.string :dh_ami_reg_med, default: "0"
        t.string :dh_ami_invasive, default: "0"
        t.string :dh_ami_respirator, default: "0"
        t.string :dh_ami_dialysis, default: "0"
        t.string :dh_ami_cpr, default: "0"
        t.string :dh_bi_cc_only, default: "0"
        t.string :dh_bi_cc_plus, default: "0"
        t.string :dh_bi_reg_med, default: "0"
        t.string :dh_bi_invasive, default: "0"
        t.string :dh_bi_respirator, default: "0"
        t.string :dh_bi_dialysis, default: "0"
        t.string :dh_bi_cpr, default: "0"
        t.string :esmc_ami_cc_only, default: "0"
        t.string :esmc_ami_cc_plus, default: "0"
        t.string :esmc_ami_reg_med, default: "0"
        t.string :esmc_ami_invasive, default: "0"
        t.string :esmc_ami_respirator, default: "0"
        t.string :esmc_ami_dialysis, default: "0"
        t.string :esmc_ami_cpr, default: "0"
        t.string :esmc_bi_cc_only, default: "0"
        t.string :esmc_bi_cc_plus, default: "0"
        t.string :esmc_bi_reg_med, default: "0"
        t.string :esmc_bi_invasive, default: "0"
        t.string :esmc_bi_respirator, default: "0"
        t.string :esmc_bi_dialysis, default: "0"
        t.string :esmc_bi_cpr, default: "0"
        t.string :nhi_ami_cc_only, default: "0"
        t.string :nhi_ami_cc_plus, default: "0"
        t.string :nhi_ami_reg_med, default: "0"
        t.string :nhi_ami_invasive, default: "0"
        t.string :nhi_ami_respirator, default: "0"
        t.string :nhi_ami_dialysis, default: "0"
        t.string :nhi_ami_cpr, default: "0"
        t.string :nhi_bi_cc_only, default: "0"
        t.string :nhi_bi_cc_plus, default: "0"
        t.string :nhi_bi_reg_med, default: "0"
        t.string :nhi_bi_invasive, default: "0"
        t.string :nhi_bi_respirator, default: "0"
        t.string :nhi_bi_dialysis, default: "0"
        t.string :nhi_bi_cpr, default: "0"

    end
    #add_index :forms, :user_id
    add_foreign_key :forms, :users
    # Column Guide- gh = "good health" (#1), dh = "deteriorating health" (#2), esmc = "end-stage medical condition"
    # nhi = no hope for improvement, ami = acute medical illness that may be treated, bi= brain illness
  end
end
